### ISSUE TITLE
how can i find the sqlite db file?

### ISSUE THREAD

**Issue by Ehco1996** [speedyHKjournalist/CosmicAndroid#3]
Thanks for your excellent work! I have two questions:

1. How can I locate the SQLite database file?
2. What will happen if I uninstall the APK and reinstall it? Will the data be lost?

**Comment by speedyHKjournalist** [comment]
Hi, 
1. It's under /data/data/com.mapleserver/, normally you don't have the permission to access this directory when the phone is not rooted, but you can export/import the file using idea/androidStudio when debug mode is enabled.
<img width="262" alt="image" src="https://github.com/speedyHKjournalist/MapleServerAndroid/assets/13363564/cd7ef332-5d4f-4bb5-82ea-78141931a2cd">. 
2. When uninstall the APK, data under /data/data/com.mapleserver/ will lost, but if you overwrite the apk without uninstall it, the data will not lost.

**Comment by speedyHKjournalist** [comment]
Maybe we can add a button to export/import db file, I will do this when I have time.

**Comment by Ehco1996** [comment]
> It's under /data/data/com.mapleserver/, normally you don't have the permission to access this directory when the phone is not rooted


Could we consider moving the database to `/sdcard/download` or another accessible location so that other applications can easily access it? This would make it more convenient for developing related tools for this server

>  but if you overwrite the apk without uninstall it, the data will not lost.

I encountered this error while attempting to update the server version. It seems I’m stuck at the moment, but no worries—I’ll restart my game and try again,thanks u efforts again 
<img width="623" alt="Screenshot 2023-12-12 at 21 01 42" src="https://github.com/speedyHKjournalist/MapleServerAndroid/assets/24697284/72a47d7f-fdde-4ff8-8c00-d0768c2b9407">

**Comment by Ehco1996** [comment]
Hey, just a heads up – I shared this project on Twitter! It’s a fantastic initiative for those keen on playing MapleStory on Android

https://x.com/Ehco1996/status/1729696815358865470?s=20

**Comment by speedyHKjournalist** [comment]
Hi, I added import export database functionality.
database will be exported to /sdcard/Download/cosmic
